Resources:
  TranslationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Translations
      AttributeDefinitions:
        - AttributeName: cache_key
          AttributeType: S
      KeySchema:
        - AttributeName: cache_key
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  TraductionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TranslationAPIFunction
      Handler: lambda_function.lambda_handler
      CodeUri: .
      Runtime: python3.11
      Timeout: 30
      MemorySize: 256
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: !GetAtt TranslationsTable.Arn
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DeepLAPIKey-*'
      Environment:
        Variables:
          DEEPL_SECRET_NAME: DeepLAPIKey
      Events:
        TranslateApi:
          Type: Api
          Properties:
            Path: /translate
            Method: post